# Generated by Django 4.1.5 on 2023-04-10 12:51

import campaign.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('primary_objective', models.CharField(choices=[(campaign.models.PrimaryObjectiveEnum['CONTENT_CREATION'], 'Content Creation'), (campaign.models.PrimaryObjectiveEnum['REACH'], 'Reach'), (campaign.models.PrimaryObjectiveEnum['ENGAGEMENT'], 'Engagement')], max_length=50)),
                ('branch', models.CharField(max_length=100)),
                ('payment_type', models.CharField(choices=[(campaign.models.PaymentTypeEnum['PAID'], 'Paid'), (campaign.models.PaymentTypeEnum['BARTER'], 'Barter')], max_length=50)),
                ('budget', models.IntegerField()),
                ('payment_delay_days', models.IntegerField()),
                ('tentative_payout', models.IntegerField()),
                ('owner_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
