# Generated by Django 4.1.5 on 2023-04-10 12:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('campaign', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='campaign',
            old_name='branch',
            new_name='brand',
        ),
    ]
