# Generated by Django 4.1.5 on 2023-04-14 10:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('campaign', '0002_rename_branch_campaign_brand'),
    ]

    operations = [
        migrations.CreateModel(
            name='Influencer',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('avg_views', models.IntegerField(blank=True)),
                ('avg_likes', models.IntegerField(blank=True)),
                ('avg_comments', models.IntegerField(blank=True)),
                ('followers', models.IntegerField(blank=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
