# Generated by Django 3.2 on 2023-04-18 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaign', '0003_influencer'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='influencers',
            field=models.ManyToManyField(blank=True, to='campaign.Influencer'),
        ),
    ]
