# Generated by Django 3.2 on 2023-04-27 13:04

from django.db import migrations

def query_set_user_influencer(apps, schema_editor):
    UserProfile = apps.get_model('user', 'UserProfile')
    Influencer = apps.get_model('user', 'Influencer')

    user5 = UserProfile.objects.get(username='user5')
    user6 = UserProfile.objects.get(username='user6')
    user7 = UserProfile.objects.get(username='user7')
    user8 = UserProfile.objects.get(username='user8')
    user9 = UserProfile.objects.get(username='user9')
    user10 = UserProfile.objects.get(username='user10')

    user5.influencer = Influencer.objects.get(id=1)
    user6.influencer = Influencer.objects.get(id=2)
    user7.influencer = Influencer.objects.get(id=3)
    user8.influencer = Influencer.objects.get(id=4)
    user9.influencer = Influencer.objects.get(id=5)
    user10.influencer = Influencer.objects.get(id=6)

    user5.save()
    user6.save()
    user7.save()
    user8.save()
    user9.save()
    user10.save()




class Migration(migrations.Migration):

    dependencies = [
        ('campaign', '0008_populate'),
    ]

    operations = [
        migrations.RunPython(query_set_user_influencer),
    ]
