# Generated by Django 3.2 on 2023-04-27 15:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_influencer_social_nullable'),
        ('campaign', '0009_populate_user_influencer_'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='campaigninfluencers',
            name='user',
        ),
        migrations.AddField(
            model_name='campaigninfluencers',
            name='influencer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='user.influencer'),
            preserve_default=False,
        ),
    ]
