# Generated by Django 3.2 on 2023-04-27 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_influencer_social_nullable'),
        ('campaign', '0010_auto_20230427_1552'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='influencers',
            field=models.ManyToManyField(blank=True, default=None, to='user.Influencer'),
        ),
        migrations.DeleteModel(
            name='CampaignInfluencers',
        ),
    ]
