# Generated by Django 4.1.5 on 2023-04-18 06:26

from django.contrib.auth import get_user_model
from django.db import migrations

def make_admin(apps, schema_editor):
    User = get_user_model()
    user = User.objects.get(username='admin')
    user.set_password('admin')


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(make_admin),
    ]
