# Generated by Django 4.1.5 on 2023-04-18 06:26

from django.contrib.auth import get_user_model
from django.db import migrations

def make_admin(apps, schema_editor):
    User = get_user_model()
    user = User.objects.create_superuser(
            username='admin',
            password='admin',
            email='admin@example.com'
            )
    # user.set_password('admin')


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_auto_20230419_1916'),
    ]

    operations = [
        migrations.RunPython(make_admin),
    ]
