# Generated by Django 3.2 on 2023-04-19 19:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_remove_userprofile_is_influencer'),
    ]

    operations = [
        migrations.CreateModel(
            name='Influencer',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('avg_views', models.IntegerField(blank=True)),
                ('avg_likes', models.IntegerField(blank=True)),
                ('avg_comments', models.IntegerField(blank=True)),
                ('followers', models.IntegerField(blank=True)),
            ],
        ),
        migrations.AddField(
            model_name='userprofile',
            name='influencer',
            field=models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='user.influencer'),
        ),
    ]
