# Generated by Django 3.2 on 2023-04-25 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_influencer_socials'),
    ]

    operations = [
        migrations.AlterField(
            model_name='influencer',
            name='avg_comments',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='influencer',
            name='avg_likes',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='influencer',
            name='avg_views',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='influencer',
            name='followers',
            field=models.IntegerField(default=0),
        ),
    ]
