# Generated by Django 3.2 on 2023-04-25 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_influencer_stats_default_0'),
    ]

    operations = [
        migrations.AlterField(
            model_name='influencer',
            name='instagram_id',
            field=models.CharField(blank=True, default=None, max_length=32, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='influencer',
            name='tiktok_id',
            field=models.CharField(blank=True, default=None, max_length=32, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='influencer',
            name='youtube_id',
            field=models.CharField(blank=True, default=None, max_length=32, null=True, unique=True),
        ),
    ]
