import './globals.css'
import { Roboto } from 'next/font/google'
import { Inter } from 'next/font/google'

const inter = Roboto({
  subsets: ['latin'],
  weight: "500"
})

export const metadata = {
  title: 'Echio',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">


      <body className={inter.className}>

        {children}

      </body>

    </html>
  )
}
