import { ThemeProvider } from '@mui/material'
import './globals.css'
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Echio',
  description: 'Generated by create next app',
}

import theme from '../../theme'

export default function RootLayout({ children }) {
  return (
    <html lang="en">

      <body className={inter.className}>

        {children}

      </body>

    </html>
  )
}
